print("Cáfe")
c1 = input("Digite o nome de um cáfe: ")
c2 = input("Digite o nome de outra marca de cáfe: ")
c3 = input("Digite o nome de outra marca de cáfe: ")
p1 = float(input(f"Qual o preço de {c1}? "))
p2 = float(input(f"Qual o preço de {c2}? "))
p3 = float(input(f"Qual o preço de {c3}? "))
print("--------------------------------------")
print(f"{c1}: R${p1:.2f}")
print(f"{c2}: R${p2:.2f}")
print(f"{c3}: R${p3:.2f}")
print("--------------------------------------")
menor = min(p1, p2, p3)
print(f"Você deve comprar {menor:.2f}")